### PR TITLE
added usage example for default_payload client parameter.

### PR DESCRIPTION
**Pull request by punkrokk**

### CODE REVIEW

**Comment by punkrokk** [comment]
took me awhile to figure this out, so here ya go :)

**Comment by rbw0** [comment]
Hello!

Hmm.. you don't need to pass a custom session object to `Client` to set `default_payload`.

The following will set "sysparm_display_value=true".

```python
...
s = pysnow.Client(instance='myinstance', 
                  user='myusername',
                  password='mypassword', 
                  default_payload={'sysparm_display_value': True}
)
...
```

Or with a custom session object, with ssl verification set to disabled, the following should do the trick:

```python
...
s = requests.Session()
s.verify = False
s.auth = requests.auth.HTTPBasicAuth('myusername', 'mypassword')

sn = pysnow.Client(instance='myinstance', 
                   session=s,
                   default_payload={'sysparm_display_value': True}
)
...
```

You're probably on a (very) old version if this doesn't work.

This is already documented in `Client`. However, there are no usage examples as you pointed out.
If you still think this needs a usage example - could you create a PR on the `dev` branch instead?

Also, I realize this isn't fully tested. If you're up for it, you could add a `default_payload` test that makes sure this dict-to-string conversion works properly.

Thanks

**Comment by rbw0** [comment]
`default_payload` is a pretty bad name, perhaps renaming to `request_params` or `request_params_dict` would be more explanatory. What do you think? Ideas?

**Comment by punkrokk** [comment]
I am updating my pull request onto dev to address my weird documentation. I agree that using the client is the way to go. I must have copied your code from above, instead of my private code that I used to implement it the way you suggest. 

I an look into writing a test, but first I'd agree with your suggestion to change default_payload to be request_params. I think if it's of type dict the _dict is redundant.

**Comment by punkrokk** [comment]
PR updated over to dev branch

**Comment by punkrokk** [comment]
I have added your requested testing. on commit [55337f7](https://github.com/rbw0/pysnow/pull/37/commits/55337f72c70de1d76b7a44a08e1c7b4cf92eb925)

**Comment by rbw0** [comment]
:+1:  nice, thanks

Yes, issuing a deprecation warning upon usage and removing in a future version is probably the best way forward. I'll have that implemented along with your code in the next release.

**Comment by punkrokk** [comment]
:)

Cheers,

JP

**Pull request merged**
