### PR TITLE
Add auto retry on some common errors

### PR DESCRIPTION
**Pull request by jcpunk**
Occasionally I open too many sessions at once at Snow and I get an error message.

The code here will automatically retry on an error for about 2 seconds and then error out as before.  

The big ones for me are 401 and 429.  (My LDAP connections limit and my operations limit).

### CODE REVIEW

**Comment by jcpunk** [comment]
hmmm not sure why the test failed...

**Comment by rbw0** [comment]
I'll have a look

**Comment by rbw0** [comment]
I've thought some about this and If this functionality were to be implemented, it should be configurable.
However, there's probably just a fraction of the pysnow users that actually needs this, and making the library more complex for just a few users isn't worth it imo.

I'll not merge this code, but will add a usage example of how to accomplish this with a custom session object to `Client`.

Thanks

**Comment by rbw0** [comment]
Created a usage example here:
http://pysnow.readthedocs.io/en/branch-0.6.9/full_examples/retry.html

**Pull request merged**
