### PR TITLE
Stub in basic unicode support for folks that use import unicode_literals

### PR DESCRIPTION
**Pull request by jcpunk**
Most of my code imports unicode_literals.  This adds detection and a test.

It should quietly work just like before on python3.

### CODE REVIEW

**Comment by rbw0** [comment]
Heyo,

Could you use the `six` library instead (and test for six.PY2 or six.PY3). It's clearer, already a requirement and imported in most modules.

Thanks

:+1:

**Comment by rbw0** [comment]
I noticed there are some tests missing, but I can build those.
Also, could you create this against branch-0.6.9?

**Comment by jcpunk** [comment]
Can do, I've not played with `six` much.  Looks like I might have an easier approach there.

**Comment by rbw0** [comment]
Nice :+1:

**Pull request merged**
